spring:
  profiles:
    active:
    - dev
---

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: springcloud-ApiGetway9000   #微服务实例名称
    prefer-ip-address: true     #显示微服务的地址 
      
spring:
  profiles: dev
  application:
    name: springcloud-apigetway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 数据库连接池
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 最小连接数
      initial-size: 5                                       # 默认连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 最大等待时长
  jpa:
    show-sql: true
 # redis:
 #   host: 10.126.2.179
 #   port: 6379
 # rabbitmq:
 #   host: 10.126.2.179
 #   port: 5672
 #   username: guest
 #   password: guest
 #   virtual-host: /  
info: #微服务详情信息
  app.name: imooc-microservicecloud-order
  company.name: www.imooc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
girl:
  name: lucy
  age: 19
  
---

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: springcloud-ApiGetway9001   #微服务名称
    prefer-ip-address: true     #显示微服务地址
      
spring:
  profiles: test
  application:
    name: springcloud-apigetway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 数据库连接池
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库最小连接数
      initial-size: 5                                       # \u521D\u59CB\u5316\u8FDE\u63A5\u6570
      max-total: 5                                          # 数据库最大连接数
      max-wait-millis: 200                                  # 数据库连接超时时间
  jpa:
    show-sql: true
 # redis:
 #   host: 10.126.2.179
 #   port: 6379
 # rabbitmq:
 #   host: 10.126.2.179
 #   port: 5672
 #   username: guest
 #   password: guest
 #   virtual-host: /    
info: #微服务详情信息
  app.name: imooc-microservicecloud-order
  company.name: www.imooc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
